// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4DJcgtjF500WBRoSIg41UMX3E2vZLKw',
    appId: '1:658835425414:web:c0ad8efea156daeab1e907',
    messagingSenderId: '658835425414',
    projectId: 'fluttertask-c38d0',
    authDomain: 'fluttertask-c38d0.firebaseapp.com',
    storageBucket: 'fluttertask-c38d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlY8upuSzoKaWG67fdWXGhOQpbwBMRug',
    appId: '1:658835425414:android:41060d8fdc41e928b1e907',
    messagingSenderId: '658835425414',
    projectId: 'fluttertask-c38d0',
    storageBucket: 'fluttertask-c38d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbeof1QmnK2GL1Z3VTnYD9-Lqa3Nqct0',
    appId: '1:658835425414:ios:a1b296d7ed325936b1e907',
    messagingSenderId: '658835425414',
    projectId: 'fluttertask-c38d0',
    storageBucket: 'fluttertask-c38d0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );
}
